### PR TITLE
Settings Feature of admin

### PR DESCRIPTION
**Pull request by eliudfromkenya**
Done with templates, now preparing to connect to the backend.

Added 3 packages
1) Axios for api connection
2) React redux for statemanagement
3) reduxjs/toolkit to simplify backend redux intergration

Installed Mukta fonts using font face
Did Redux and Axios configurations.

Worked of Admin dashboard feature

### CODE REVIEW

**Comment by peculiaruc** [comment]
@eliudas, @adeniranjohn and I will be here to guide you on how to fix the Codacy errors. 

Click on Details
Then resolve to see them, go through and ask questions, please. Tag me if need be

**Comment by eliudfromkenya** [comment]
Thanks so much.

**Comment by peculiaruc** [comment]
> Reference

Again send PR in batches so you do not have so many Codacy errors. Create a branch for at least 2 pages and send a PR as soon as you are done with it.

**Comment by adeniranjohn** [comment]
Hi Eliud. 

Kindly click on the url below to show the codacy errors and use it to fix it accordingly. 

https://app.codacy.com/gh/ALCOpenSource/Mentor-Management-System-Team-3/pullRequest?prid=11712051

Well done Eliud.

**Comment by peculiaruc** [comment]
@eliudfromkenya This issue correction just remains only 7. You should not need to close it.  Let me have a call with you. Fix a time today.

**Comment by eliudfromkenya** [comment]
Thanks so much.I will really appreciate.I have tried for 2 days, but the errors are not going away.
Am available anytime, as soon as possible. 
 
  On Thu, 11 May 2023 at 3:55 pm, Peculiar C. ***@***.***> wrote:   


@eliudfromkenya This issue correction just remains only 7. You should not need to close it. Let me have a call with you. Fix a time today.

**Pull request closed without merging**
